name: Configure Netlify

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"

env:
  TF_CLOUD_ORGANIZATION: "ivayhabimana"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "spotlight"
  CONFIG_DIRECTORY: "./terraform"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.1

      - name: Upload configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload-config
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          token: ${{ env.TF_API_TOKEN }}
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          token: ${{ env.TF_API_TOKEN }}
          workspace: ${{ env.TF_WORKSPACE }}

      - name: Apply run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        if: fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply-run
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          token: ${{ env.TF_API_TOKEN }}
          run: ${{ steps.create-run.outputs.run_id }}
